# build libsql-server
FROM rust:slim-bullseye as builder
RUN apt update

RUN apt install -y libclang-dev clang \
        build-essential tcl protobuf-compiler file \
        libssl-dev pkg-config

RUN apt clean
RUN update-ca-certificates

WORKDIR /libsql-server
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/libsql-server/target \
    cargo build -p libsql-server --release && \
    cp target/release/libsql-server /libsql-server/bin


# runtime
FROM debian:bullseye-slim
RUN apt update

COPY --from=builder /libsql-server/bin /bin/libsql-server
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY docker-entrypoint.sh /usr/local/bin

VOLUME [ "/var/lib/libsql-server" ]

RUN groupadd --system --gid 666 libsql-server
RUN adduser --system --home /var/lib/libsql-server --uid 666 --gid 666 libsql-server
USER libsql-server
WORKDIR /var/lib/libsql-server

EXPOSE 5001 8080

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["/bin/libsql-server"]
